### PR TITLE
allow players to be banned by only using first name

### PR DESCRIPTION
**Pull request by Pietrodjaowjao**

### CODE REVIEW

**Comment by Ultradragon005** [comment]
BLACK

**Comment by NikoCat233** [comment]
bro u think they are lazy to change codes? lol

**Comment by Pietrodjaowjao** [comment]
?? 
image
No one has time to write the same friend code 10k times.

**Comment by NikoCat233** [comment]
lmao

**Comment by NikoCat233** [comment]
i guess next time there gonna be Pietrodjaowjao

**Pull request merged**
