### PR TITLE
Made setting to change the number of shrooms you need to click to open the door (for fungle)

### PR DESCRIPTION
**Pull request by FuroYT**
The only problem is that i didnt found a way to override the shroom spawn limit so its limited to 6 max for now

(if you wanna fix my code go ahead i think it kinda suck)

### CODE REVIEW

**Comment by Tommy-XL** [comment]
It's work fine for vanilla players?

**Comment by NikoCat233** [comment]
no it does not work for vanilla

**Comment by FuroYT** [comment]
I dont Know how to change the vanilla player’s Game react to that so ill just change il to draft

**Comment by NikoCat233** [comment]
This should be impossible if u dont mod vanilla players

**Comment by Tommy-XL** [comment]
A little later I will try to fix this for vanilla players

**Comment by Tommy-XL** [comment]
It's probably not really possible, but I'm not sure about it

**Comment by FuroYT** [comment]
At least 50% is done

**Comment by Tommy-XL** [comment]
Well, I checked and unfortunately it is not possible to implement this for vanilla players

**Pull request closed without merging**
