### PR TITLE
Fix Double Assign Role

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Gurge44** [comment]
What about the "Maximum" setting?
If someone wants multiple of the same role....

**Comment by Tommy-XL** [comment]
hmm

**Comment by Tommy-XL** [comment]
What about this?

image

**Comment by Tommy-XL** [comment]
Oh, this won't work lol

**Comment by Tommy-XL** [comment]
> What about the "Maximum" setting? If someone wants multiple of the same role....

Fixed
https://github.com/0xDrMoe/TownofHost-Enhanced/pull/709

**Pull request merged**
