### PR TITLE
Update Cancel Vote System for certain roles

### PR DESCRIPTION
**Pull request by NikoCat233**
This will be a very very long existing pr.
The first vote is for skill and will be returned.
The second vote will be your real vote.
If the first vote target quits, the skill will not be returned.

Role to work with
- [ ] Cleanser
- [ ] Eraser
- [ ] Dictator
- [ ] Divinator
- [ ] Tracker
- [ ] Keeper (update with notify)
- [ ] Oracle
- [ ] Godfather

Extra
- [ ] /vote command https://discord.com/channels/1094344790910455908/1194665588174372974

Pls help check whether im missing any roles

### CODE REVIEW

**Comment by Tommy-XL** [comment]
> [ ] Dictator

I don't think Dictator needs this

**Comment by Ultradragon005** [comment]
> This will be a very very long existing pr. The first vote is for skill and will be returned. The second vote will be your real vote. If the first vote target quits, the skill will not be returned.
> 
> Role to work with
> 
> * [ ]  Cleanser
> * [ ]  Eraser
> * [ ]  Dictator
> * [ ]  Divinator
> * [ ]  Tracker
> * [ ]  Keeper (update with notify)
> * [ ]  Oracle
> 
> Extra
> 
> * [ ]  /vote command https://discord.com/channels/1094344790910455908/1194665588174372974
> 
> Pls help check whether im missing any roles

fortune teller

**Comment by Gurge44** [comment]
> > This will be a very very long existing pr. The first vote is for skill and will be returned. The second vote will be your real vote. If the first vote target quits, the skill will not be returned.
> > Role to work with
> > 
> > * [ ]   Cleanser
> > * [ ]   Eraser
> > * [ ]   Dictator
> > * [ ]   Divinator
> > * [ ]   Tracker
> > * [ ]   Keeper (update with notify)
> > * [ ]   Oracle
> > 
> > Extra
> > 
> > * [ ]   /vote command https://discord.com/channels/1094344790910455908/1194665588174372974
> > 
> > Pls help check whether im missing any roles
> 
> fortune teller

Fortune Teller == Divinator

**Comment by Gurge44** [comment]
Godfather is missing

**Comment by Ultradragon005** [comment]
> Fortune Teller == Divinator

oh.

**Comment by ryuk201198** [comment]
> This will be a very very long existing pr. The first vote is for skill and will be returned. The second vote will be your real vote. If the first vote target quits, the skill will not be returned.
> 
> Role to work with
> 
> * [ ]  Cleanser
> * [ ]  Eraser
> * [ ]  Dictator
> * [ ]  Divinator
> * [ ]  Tracker
> * [ ]  Keeper (update with notify)
> * [ ]  Oracle
> 
> Extra
> 
> * [ ]  /vote command https://discord.com/channels/1094344790910455908/1194665588174372974
> 
> Pls help check whether im missing any roles

Keeper already does that..

**Comment by xXkadziXx** [comment]
> This will be a very very long existing pr. The first vote is for skill and will be returned. The second vote will be your real vote. If the first vote target quits, the skill will not be returned.
> 
> Role to work with
> 
> * [ ]  Cleanser
> * [ ]  Eraser
> * [ ]  Dictator
> * [ ]  Divinator
> * [ ]  Tracker
> * [ ]  Keeper (update with notify)
> * [ ]  Oracle
> 
> Extra
> 
> * [ ]  /vote command https://discord.com/channels/1094344790910455908/1194665588174372974
> 
> Pls help check whether im missing any roles

What about Swapper?

**Comment by NikoCat233** [comment]
I got exams to prepare these days , so this pr probably will be hanged lol

**Comment by NikoCat233** [comment]
/vote will be done simply using castvote

**Comment by xXkadziXx** [comment]
> This will be a very very long existing pr. The first vote is for skill and will be returned. The second vote will be your real vote. If the first vote target quits, the skill will not be returned.
> 
> Role to work with
> 
> * [ ]  Cleanser
> * [ ]  Eraser
> * [ ]  Dictator
> * [ ]  Divinator
> * [ ]  Tracker
> * [ ]  Keeper (update with notify)
> * [ ]  Oracle
> * [ ]  Godfather
> 
> Extra
> 
> * [ ]  /vote command https://discord.com/channels/1094344790910455908/1194665588174372974
> 
> Pls help check whether im missing any roles

Soul Collector?
Also add a setting to make SC can predict more than once per meeting

**Comment by NikoCat233** [comment]
Not doing this lol

**Comment by Tommy-XL** [comment]
Rip

**Pull request closed without merging**
