### PR TITLE
Make updater not async (because of crashes) and now based on timestamp

### PR DESCRIPTION
**Pull request by Pietrodjaowjao**

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
Credit also goes to nikocat, i used his fork as base but wasnt able to pr in his repo

**Comment by NikoCat233** [comment]
I'm also doing other change in my pr, is it ok that I merge your pr into mine?

**Comment by Ultradragon005** [comment]
the pr ceptions go crazy

**Comment by Tommy-XL** [comment]
Soo, I close it?

**Comment by Pietrodjaowjao** [comment]
ok

**Comment by Pietrodjaowjao** [comment]
close it

**Pull request closed without merging**
