### PR TITLE
Return Horse mode and prepare for 1st april update

### PR DESCRIPTION
**Pull request by Pietrodjaowjao**

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
Finally fixed all the issues bro, i recommend to merge this in 1st april

**Comment by Pietrodjaowjao** [comment]
ig you could just merge this... there is 2 days remaining for the release lol and the update was already leaked

**Comment by Ultradragon005** [comment]
I think people are celebrating easter

**Comment by Pietrodjaowjao** [comment]
just like 3 hours remaining

**Comment by Tommy-XL** [comment]
I was planning to add this for v2.0.0

**Comment by Pietrodjaowjao** [comment]
why?

**Comment by Tommy-XL** [comment]
Because the next version 1.6.0 is planned for full release, but without ghost roles, especially since the April Fool's joke will go on for another week and may cause some problems

**Comment by Tommy-XL** [comment]
image

Wouldn't it be better to always display this banner?
Since if the host activates it, then it will be activated for others clients

And Horse Mode will remain a client setting

**Comment by Pietrodjaowjao** [comment]
cant we make the gamemode change midgame instead

**Comment by Pietrodjaowjao** [comment]
when toggle is on

**Comment by Tommy-XL** [comment]
But it is activated only for host

**Comment by Pietrodjaowjao** [comment]
i mean that we can change GameMode then sync rpc, so body types will change

**Comment by Tommy-XL** [comment]
This is not bad, but the current code doesn't do it?

**Comment by Pietrodjaowjao** [comment]
Yeah it doenst, i will fix tomorrow.

**Comment by Pietrodjaowjao** [comment]
ig its impossible bc other players would need to rejoin

**Comment by Pietrodjaowjao** [comment]
just merge after the april 8 maybe, the event will end that time

**Comment by Tommy-XL** [comment]
> image
> 
> Wouldn't it be better to always display this banner? Since if the host activates it, then it will be activated for others clients
> 
> And Horse Mode will remain a client setting

Well, you can just do it as I suggested, the current code only applies to modded players, although it can be done for other players, although you will have to create new lobbies for this

**Comment by Pietrodjaowjao** [comment]
ok

**Comment by Pietrodjaowjao** [comment]
There is a way to fix the heads clipping trought walls, its just a shader issue, but since it will only work for who have tohe installed, ig i will not put

**Comment by Pietrodjaowjao** [comment]
Ready to merge

**Pull request merged**
