### PR TITLE
Support Hide And Seek (real)

### PR DESCRIPTION
**Pull request by Ultradragon005**
I mean, I didn't change anything at all, but it works perfectly fine for me.
image
This error pops up the first time you try to create a HnS game, but therafter dosen't. (same stupid shit was happening with normal role settings menu, but we overriden that so it isn't noticeable)

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Do you want to do this for 2.0.0?

**Comment by Tommy-XL** [comment]
I mean that there is still a chance to add support in Canary 12 and in the release version, but you need to be sure that it works

**Comment by Ultradragon005** [comment]
> Do you want to do this for 2.0.0?

Oh, I mean we could. There's one mroe thign I have to do which is disabling switch gamemode thing if in HnS

**Comment by Ultradragon005** [comment]
> I mean that there is still a chance to add support in Canary 12 and in the release version, but you need to be sure that it works

mhm, I was going to run some public tests to make sure

**Comment by Ultradragon005** [comment]
> There's just one more thing I have to do which is disabling switch gamemode thing if in HnS

Okay, so this stuff has to be done manually, so I'll simply put it here cuz might aswell
image

**Comment by abdullah2007dhtjtr** [comment]
How can i play Hide N Seek

**Comment by Tommy-XL** [comment]
Bro

**Comment by Ultradragon005** [comment]
> Okay, so this stuff has to be done manually

okay nvm I find an easier fix, I just wanted an excuse to do this lmao 😂 Guess I'll jsut do it in a future PR then

**Comment by abdullah2007dhtjtr** [comment]
what can i do to play Hide N Seek

**Comment by Tommy-XL** [comment]
> what can i do to play Hide N Seek

Wait next Canary or release version bro

**Comment by abdullah2007dhtjtr** [comment]
but how he opened hide n seek

**Comment by Tommy-XL** [comment]
> but how he opened hide n seek

Because he's a developer mod, lol

**Comment by abdullah2007dhtjtr** [comment]
hey dev

**Comment by abdullah2007dhtjtr** [comment]
wait

**Comment by abdullah2007dhtjtr** [comment]
he still working on it

**Comment by Tommy-XL** [comment]
Lmao if you really want to play hide and seek why don't you start a vanilla AU

**Comment by abdullah2007dhtjtr** [comment]
wdym

**Comment by abdullah2007dhtjtr** [comment]
you want to play hide n seek without mod

**Comment by Ultradragon005** [comment]
all good

**Comment by Tommy-XL** [comment]
image

**Comment by Ultradragon005** [comment]
done

**Comment by abdullah2007dhtjtr** [comment]
> done

hey

**Comment by abdullah2007dhtjtr** [comment]
heey dev

**Comment by Dxgamer7405** [comment]
aint no way

**Comment by abdullah2007dhtjtr** [comment]
hi

**Comment by Pietrodjaowjao** [comment]
hey @abdullah2007dhtjtr

**Comment by Pietrodjaowjao** [comment]
want hide n seek @abdullah2007dhtjtr

**Comment by abdullah2007dhtjtr** [comment]
yes

**Comment by abdullah2007dhtjtr** [comment]
he said he done how can i use this code

**Comment by Tommy-XL** [comment]
> he said he done how can i use this code

Bro, wait for the next Canary or release version

**Pull request merged**
