### PR TITLE
Port a few TOH (taken from TOHE+) roles.

### PR DESCRIPTION
**Pull request by Ultradragon005**
- [x] Check if Stealth Works.
- [x] Check if penguin works.
- [x] Check if PlageDoctor (Plague Scientist) works.

### CODE REVIEW

**Comment by Ultradragon005** [comment]
image
OH LOL, I'm dumb, well whatever

**Comment by Ultradragon005** [comment]
@Tommy-XL @ryuk2098 okay, it can be reviewed!

**Comment by Tommy-XL** [comment]
i will check later

**Comment by Tommy-XL** [comment]
Fix conflicts pls

**Review by Tommy-XL — APPROVED** [review]

**Comment by Ultradragon005** [comment]
@Tommy-XL done!

**Pull request merged**
