### PR TITLE
Add Scanner for overseer

### PR DESCRIPTION
**Pull request by Ultradragon005**
visualtasks or not dosen't matter because in the rpc it dosen't check for that, only in innersloth's own method it does

### CODE REVIEW

**Comment by Gurge44** [comment]
Yeah Herbalist in PL also used this

**Comment by Tommy-XL** [comment]
I hope this doesn't cause disconnects when constantly sending rpc lol

**Comment by Ultradragon005** [comment]
> I hope this doesn't cause disconnects when constantly sending rpc, lol

uh... have you like..... seen glitch or chronomancer 💀 they're spamming changenamerpc almost every second

**Comment by Ultradragon005** [comment]
and seems to be perfectly fine 😼

**Pull request merged**
