### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by 0xDrMoe**

### CODE REVIEW

**Review by Tommy-XL — APPROVED** [review]

**Comment by Tommy-XL** [comment]
Yes, have to wait for approval from other people to combine your PR ._.

**Comment by Tommy-XL** [comment]
wtf

**Comment by 0xDrMoe** [comment]
wtf is happening

**Comment by Tommy-XL** [comment]
idk, lol

**Comment by 0xDrMoe** [comment]
nah cuz its just wrong

**Comment by Tommy-XL** [comment]
Chinese translation is present in Russian

image

**Comment by 0xDrMoe** [comment]
i know

**Comment by Tommy-XL** [comment]
Now all files contain English ._.

**Comment by 0xDrMoe** [comment]
check crowdin :((((((

**Comment by Tommy-XL** [comment]
I think this can be closed? Because there are too many commits and it eventually broke the translation in crowdin

**Comment by 0xDrMoe** [comment]
Bugged out from Crowdin, unnecessary PR

**Pull request closed without merging**
