### PR TITLE
Add Obfuscation Attribute

### PR DESCRIPTION
**Pull request by NikoCat233**
Exclude All prefix and postfix by .*fix.*
And tohe can then be confused by dotfuscator

Need to exclude all enum
And RoleBase's role name need to stay same with the one in CustomRoles

### CODE REVIEW

**Comment by Tommy-XL** [comment]
I don't quite understand why this is needed

**Comment by NikoCat233** [comment]
Yeah its for my personal usage actually

**Comment by NikoCat233** [comment]
Maybe one day someone gonna build a private build? LOL

**Comment by Ultradragon005** [comment]
wtf... so ur just gonna do it for each time any new role comes out ?? WHy isn't it possible to simply disable dotfuscator when working with tohe, it's open source

**Comment by NikoCat233** [comment]
Not a hard thing actually
Just make sure all the Prefix Postfix has a Prefix Postfix
And add [Obfuscation(exclude = true, applytomembers = false)] before the rolebase name

**Comment by NikoCat233** [comment]
Actually it gonna be useful if we gonna bring back things like EAC cloud report and services like the original TOHEdited cloud matchmaking

**Comment by NikoCat233** [comment]
I think a better solution is to add stuffs like
RoleBase.thisrole => customroles.wtf

And register the rolebase based on this variable

**Comment by Ultradragon005** [comment]
💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀

**Comment by Pietrodjaowjao** [comment]
what the fuck did i just see

**Comment by Dxgamer7405** [comment]
i dont understand why this since the mod is open source and if you acidently leak a dll file its kinda your fault lol

**Comment by Ultradragon005** [comment]
better yet, let's jsut write code like this 
image

**Comment by Pietrodjaowjao** [comment]
will this even work?

**Comment by Ultradragon005** [comment]
https://www.youtube.com/embed/OWZ5tsCYD_M?autoplay=1&rel=0

**Comment by Ultradragon005** [comment]
lemme test if some how image attribute will work for it: 
video

**Pull request closed without merging**
