### PR TITLE
Support map dlekS ehT

### PR DESCRIPTION
**Pull request by Tommy-XL**
Thanks @Galster-dev for #115

- [x] Fix conflicts in code
- [x] Add position for map in `GetBlackRoomPosition()`
- [x] Add a warning message about broken vents
- [x] Test Disable Devices
- [x] Test Random Spawn

### CODE REVIEW

**Comment by Galster-dev** [comment]
any progress on this?

**Comment by Tommy-XL** [comment]
> any progress on this?

I was going to done it this weekend

**Comment by Tommy-XL** [comment]
Everything seems to be working fine (except for the vents of course)

**Comment by Ultradragon005** [comment]
> Everything seems to be working fine (except for the vents of course)

Ouch! so no vent-based roles (like chameleon or swooper) works, I presume?

**Comment by Tommy-XL** [comment]
> Ouch! so no vent-based roles (like chameleon or swooper) works, I presume?

On this map - yes

**Pull request merged**
