### PR TITLE
Fix Egoist win text

### PR DESCRIPTION
**Pull request by KingPanda360**

### CODE REVIEW

**Comment by Ultradragon005** [comment]
and what if multiple egost wins 🤨

**Comment by Ultradragon005** [comment]
> Is that possible? I thought there could only be one egoist in a game.
it is. also in the winnercheck code it cheks for multiple egoists of the same team
image

**Comment by Ultradragon005** [comment]
I mean you can just do Egoist(s) Win!

**Comment by KingPanda360** [comment]
I was thinking that, but I was wondering if people would get confused by it.

**Comment by Ultradragon005** [comment]
there could be 2 texts, but idk who wants top code that

**Comment by KingPanda360** [comment]
> there could be 2 texts, but idk who wants to code that

If someone wants to do that, they could make a separate PR, and this one can be closed without merging.

**Pull request merged**
