### PR TITLE
Add FodyWeavers.xsd

### PR DESCRIPTION
**Pull request by Tommy-XL**
Not sure what this is for, but it looks like it's needed

### CODE REVIEW

**Comment by Tommy-XL** [comment]
I can’t approve my PR, but need at least 2 approvals ._.

**Comment by NetherDragonTw** [comment]
> I can’t approve my PR, but need at least 2 approvals ._.

so sad

**Review by 0xDrMoe — APPROVED** [review]

**Comment by 0xDrMoe** [comment]
this is good

**Comment by Tommy-XL** [comment]
But there is a problem, how will I add my changes if I cannot approve my PRs, but other PRs are approved and merged

**Pull request merged**
