### PR TITLE
Added a warning for epilepsy patients in the welcome message (SChinese)

### PR DESCRIPTION
**Pull request by CrewCyan**
Added a warning for epilepsy patients in the welcome message (SChinese),I don't want anyone to have a seizure due to playing this mod (although it sounds unlikely)

### CODE REVIEW

**Comment by LezaiYa** [comment]
我觉得，通过另一种方式来表达可能会更好，而不是加到欢迎语里面

**Comment by CrewCyan** [comment]
> 我觉得，通过另一种方式来表达可能会更好

那你觉得以怎样的方式表达会更好，比如添加在公告里？

**Comment by LezaiYa** [comment]
新增加一个`welcome`专门写癫痫警告，也许会更好

**Review by Tommy-XL — APPROVED** [review]

**Comment by Tommy-XL** [comment]
I think this is a work in progress?

**Comment by CrewCyan** [comment]
> I think this is a work in progress?

This pull request can merged.  I don't have time to add LezaiYa's suggestions right now, so you can merge them first.

**Pull request closed without merging**
