### PR TITLE
TextBoxPatch (Port from EHR)

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
What about vanilla lobbies? if you dont revert its instaban

**Comment by MargaretTheFool** [comment]
what does this even do

**Comment by Gurge44** [comment]
allows writing of any character

**Comment by Tommy-XL** [comment]
Erm, what the sigma?

**Comment by Ultradragon005** [comment]
gyatt level 9001

**Comment by Ultradragon005** [comment]
image

**Pull request merged**
