### PR TITLE
Hater no longer ignores shields & Code improvement

### PR DESCRIPTION
**Pull request by Gurge44**
I don't have time to test anything, so I would apprechiate if someone could. Thanks.

### CODE REVIEW

**Comment by NikoCat233** [comment]
Im testing it later

**Comment by NikoCat233** [comment]
Bug:
1.shield wont take off after FFF's kill attempt
2.FFF still wins even it target got shield protects

Bruh idk how 2 fix this

**Comment by Gurge44** [comment]
Well yea.... the whole winner condition code needs to be moved into MurderPlayerPatch. It would make it a lot easier to work with and we could avoid using RpcCheckAndMurder(), since the code will only run when the Hater actually kills. I'll make this when I get home.

**Comment by NikoCat233** [comment]
Suggest directly move check murder 2 murder player

**Comment by NikoCat233** [comment]
Also the string of FFF needs to be updated

**Comment by NikoCat233** [comment]
No not me , I got classes to attend the whole day =(

**Comment by NikoCat233** [comment]
Tested and it works fine! Just add more logger

And thanks for the detailed comments, You truly made me understand everything

**Comment by Gurge44** [comment]
I think it can be merged if others are ok with it, you can add more logging later

**Pull request merged**
