### PR TITLE
/quit setting to prevent hackers or player to ban themselves

### PR DESCRIPTION
**Pull request by FuroYT**

### CODE REVIEW

**Comment by NikoCat233** [comment]
Can u pls also make eac not kick untrusted rpc player?

**Comment by FuroYT** [comment]
what do you mean?

**Comment by NikoCat233** [comment]
image
Here add
cheatoptions.cancel return false;

**Comment by FuroYT** [comment]
im so dumb i still dont understand 💀

**Comment by NikoCat233** [comment]
if (options.cheatresponse.getint() == 5)
{
Logger.info("Cancel action bcz cheat response is cancel.", "MalumMenu on top!")
return false;
}
add before switch

**Comment by NikoCat233** [comment]
thx!

**Comment by Tommy-XL** [comment]
Omg, why so many changes
image

**Comment by FuroYT** [comment]
ur welcome

**Comment by FuroYT** [comment]
Now with that pr being done
if this pr get merged we can pull the middle finger on Silast

**Comment by FuroYT** [comment]
> Omg, why so many changes image

visual studio changing json spaces to tabs idk

**Comment by NikoCat233** [comment]
auto format LOL

**Comment by NikoCat233** [comment]
Also pls return false in ChatControllerPatch.onReceiveChat
if the playercontrol of the sender is host

**Comment by Tommy-XL** [comment]
> visual studio changing json spaces to tabs idk

I'm just afraid that Crowdin will simply clear the entire translation

**Comment by NikoCat233** [comment]
Ok i will do this myself when i get the time

**Comment by FuroYT** [comment]
> > visual studio changing json spaces to tabs idk
> 
> I'm just afraid that Crowdin will simply clear the entire translation

if you want i revert the json and you can add the json entry so it doesnt break

**Comment by Tommy-XL** [comment]
> if you want i revert the json and you can add the json entry so it doesnt break

Ok

**Comment by FuroYT** [comment]
`"PlayerCanUseQuitCommand": "Players can use the /quit command to leave the lobby forever"`

@Tommy-XL here is the string

**Review by Tommy-XL — APPROVED** [review]

**Pull request merged**
