### PR TITLE
fix nimble getting removed even when cant be stolen

### PR DESCRIPTION
**Pull request by ryuk201198**

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Lol, I don’t understand how this fixes the bug if SubRoles is already has List

**Comment by Tommy-XL** [comment]
Thanks github
image

**Comment by ryuk201198** [comment]
> Lol, I don’t understand how this fixes the bug if SubRoles is already has List

If i dont do `.ToList()` then `AllSubRoles` is just a reference to the same list that `Main.PlayerStates[Target.PlayerId].SubRoles` points to. If I removed anything from `AllSubRoles` it was being removed from `Main.PlayerStates[Target.PlayerId].SubRoles` as well. 

By adding `.ToList()`, `AllSubRoles` will be a new list rather than referencing the original  list `Main.PlayerStates[Target.PlayerId].SubRoles`

**Comment by Tommy-XL** [comment]
Oh, I got it

**Review by Tommy-XL — APPROVED** [review]

**Comment by Tommy-XL** [comment]
Why can't I merge this PR?

**Comment by Tommy-XL** [comment]
Ok, I did it myself
https://github.com/0xDrMoe/TownofHost-Enhanced/commit/97cd8de56eb1adb86b4057b3f2ce0af931c2db8b

**Pull request closed without merging**
