### PR TITLE
Fix critical bug in the software.

### PR DESCRIPTION
**Pull request by VillainsRule**
This fixes the long-standing bug involving Dictator being improperly named.
This PR must be merged **now**.

### CODE REVIEW

**Comment by NikoCat233** [comment]
Good pr, good work!

**Comment by NikoCat233** [comment]
"This should really be on scene when we are on April Fool LOL"

**Comment by Gurge44** [comment]
🤣

**Review by Gurge44 — APPROVED** [review]

**Comment by Gurge44** [comment]
Just for the sake of it lmao

**Comment by Gurge44** [comment]
Everyone approve it

**Review by NikoCat233 — APPROVED** [review]
Exactly

**Review by Ultradragon005 — APPROVED** [review]
These changes are absolutely magnificent, mr. Plaguer you are applauded with the greatest of trophies. We hereby avoke our unit to make you our next team leader, see you soon ;)

**Review by LezaiYa — APPROVED** [review]

**Review by Loonietunes — APPROVED** [review]
my god, how, when, you are so good at coding, please tach me so I don't have to rely on porting roles, it is sooo hardddd

**Comment by Tommy-XL** [comment]
What's going on here lol

**Comment by spuhnj** [comment]
Amazing and great add now

**Comment by LezaiYa** [comment]
> What's going on here lol

Just take a look at what the file changes and you'll see

**Comment by Ultradragon005** [comment]
> What's going on here lol

他们正在将外星人显化到地球上，哦，上帝，请帮助，派遣援助！

**Comment by Loonietunes** [comment]
image
TELL THIS STUPID KID, THAT I AIN'T NO ALT ACCOUNT, I*M THE REAL DEAL,. DON'T MISTAKE ME FOR THIS "IMPOSTOR" MOD TOH:EWNHANCED, I AM NOT IMPOSTOR MOD

**Comment by Tommy-XL** [comment]
...

**Comment by spuhnj** [comment]
hi loone tunes :hehe:

**Comment by Loonietunes** [comment]
> hi loone tunes :hehe:

hi cutiepie

**Comment by Loonietunes** [comment]
remind me to call moe a bitch by evening, k ?

**Comment by spuhnj** [comment]
🧍‍♂️

**Comment by CrewCyan** [comment]
> image告诉这个愚蠢的孩子，我不是ALT帐户，我*是真正的交易。不要把我误认为是这个“冒名顶替者”模组 TOH：EWNHANCED，我不是冒名顶替者模组

I already know that this is not a pirated mod. I admit my mistake, but at the same time I hope loonie and moe can solve the contradiction peacefully. Whoever is wrong will apologize, and at the same time admit his mistake (I am not biased towards any side) and don't escape from the facts.

**Comment by Tommy-XL** [comment]
well

**Comment by CrewCyan** [comment]
> > 图像告诉这个愚蠢的孩子，我不是ALT帐户，我*是真正的交易。不要把我误认为是这个“冒名顶替者”模组 TOH：EWNHANCED，我不是冒名顶替者模组
> 
> 我已经知道这不是盗版模组。我承认我的错误，但同时我希望你和萌能够和平地解决矛盾。谁错了，谁就要道歉，同时承认自己的错误（我不偏袒任何一方），不要逃避事实。

I hope the contradiction can be resolved peacefully.

**Comment by Tommy-XL** [comment]
It's funny
image

**Comment by Loonietunes** [comment]
> > > 图像告诉这个愚蠢的孩子，我不是ALT帐户，我*是真正的交易。不要把我误认为是这个“冒名顶替者”模组 TOH：EWNHANCED，我不是冒名顶替者模组
> > 
> > 
> > 我已经知道这不是盗版模组。我承认我的错误，但同时我希望你和萌能够和平地解决矛盾。谁错了，谁就要道歉，同时承认自己的错误（我不偏袒任何一方），不要逃避事实。
> 
> I hope the contradiction can be resolved peacefully.

First tell moe to marry me, then we can talk. oops, sorry, no I didn't mean that, you didn't see nothing. uhm... pretend like I was never here.

**Comment by spuhnj** [comment]
Guys that's a fake account 😭

**Comment by Ultradragon005** [comment]
☠👻👽👾👾👾

**Comment by NikoCat233** [comment]
No im sure its a real alt🤣

**Comment by laikrai** [comment]
Ain't no way this is real 💀

**Comment by NikoCat233** [comment]
Lol

**Pull request closed without merging**
