### PR TITLE
Modded Non-Host Mark fix + more

### PR DESCRIPTION
**Pull request by D1GQ**
# Overview
Fix a issue with Modded Non-Host clients marks not working and more!
# Futures
```diff
+ | Added RPC to receive players marks from the host.
+ | Added list of saved players marks.
```

### CODE REVIEW

**Comment by Ultradragon005** [comment]
uh.. there is like a WHOLE thing which this ignore
image

**Comment by Ultradragon005** [comment]
also isn't playercontrol patch already for modded clients 
image

**Comment by D1GQ** [comment]
> also isn't playercontrol patch already for modded clients image

Yes, I think you're missing the point that this is for modded clients that aren't the host.

**Comment by Ultradragon005** [comment]
> Yes, I think you're missing the point that this is for modded clients that aren't the host.

playercontrol.localplayer is the moddedplayer

**Comment by D1GQ** [comment]
> playercontrol.localplayer is the moddedplayer
> 
> It will activate for all players who have the mod installed and host

All modded players others than the host cannot get mark information because all of the roles are only ran through the host, so the GetMark override doesn't work. So to fix it we have to retrieve the information from the host.

**Comment by Ultradragon005** [comment]
then it's better to do 

sendrpc:
writer.writnetobject{target};
writer.write($"{realname}{deathreason}{mark}{suffix}")


recievierpc:

target.cosmetics.nametext.text = reader.readstring();

**Comment by D1GQ** [comment]
> sendrpc: writer.writnetobject{target}; writer.write($"{realname}{deathreason}{mark}{suffix}")
> 
> recievierpc:
> 
> target.cosmetics.nametext.text = reader.readstring();

I'll see what I can change tomorrow.

**Comment by Tommy-XL** [comment]
Anyway fixed

**Pull request closed without merging**
