### PR TITLE
Add /me command

### PR DESCRIPTION
**Pull request by NikoCat233**
image
image

### CODE REVIEW

**Comment by Ultradragon005** [comment]
who would need to know their has-puid other than devs 
image

**Comment by NikoCat233** [comment]
Later i will add whitelist and mod list based on hashpuid
so you can use them on custom servers

**Comment by Pietrodjaowjao** [comment]
Hi [1] Niko233!

Your ip address is 192.62.215.234

**Comment by Ultradragon005** [comment]
> Hi [1] Niko233!
> 
> Your ip address is 192.62.215.234

image

**Pull request merged**
