### PR TITLE
Recode random spawn (Code ported from TOH)

### PR DESCRIPTION
**Pull request by Tommy-XL**
Port code from: https://github.com/tukasa0001/TownOfHost/blob/main/Patches/RandomSpawnPatch.cs

### CODE REVIEW

**Comment by NikoCat233** [comment]
It doesnt fix

**Comment by NikoCat233** [comment]
+4 and +8 will soon be overwritten by client

**Comment by Tommy-XL** [comment]
This fixes it, but players are not teleport forced while moving and I can't test this due to servers

**Comment by Tommy-XL** [comment]
I renamed PR

**Comment by Tommy-XL** [comment]
Seems work fine

**Pull request merged**
