### PR TITLE
Specific Turn On Chat

### PR DESCRIPTION
**Pull request by NikoCat233**
Example pr, dont merge.
If we really gonna add this, we will need to do shxt like specific AntiBlackOut LOL

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Can you sync with main?
I merge this but this code won't be used for now

**Comment by Tommy-XL** [comment]
Bruh, again conflicts

**Comment by NikoCat233** [comment]
Jesus

**Comment by NikoCat233** [comment]
I can't see this conflict on my local github damn

**Comment by NikoCat233** [comment]
Ok

**Pull request merged**
