### PR TITLE
Remove unnecessary error log in on player joined patch

### PR DESCRIPTION
**Pull request by NikoCat233**

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
Make it kick if the playercontrol is still null, also recommend to put 2.5f in LateTask delay

**Comment by NikoCat233** [comment]
It will never kick i guess
Bcz player control is always spawned on host side i guess

**Comment by Pietrodjaowjao** [comment]
no, the host only accepts the spawn, but the one who spawns is the player joining

**Comment by NikoCat233** [comment]
Is it possibe for host to check client side player control spawn?

**Comment by Pietrodjaowjao** [comment]
yes

**Comment by NikoCat233** [comment]
Wtf this is turned to draft

**Comment by NikoCat233** [comment]
This code is already completed.

**Pull request merged**
