### PR TITLE
Merge sync role skill rpc into one - Part1+2 - Crewmate/Impostor roles

### PR DESCRIPTION
**Pull request by NikoCat233**
Most roles' sync skill rpc can be directly changed into one
By writing (int)Customroles at the head
And let the SyncRoleSkillReader read and pass to their ReceiveRpc

### CODE REVIEW

**Comment by NikoCat233** [comment]
Merge the part 1 and see the effects

**Comment by Tommy-XL** [comment]
I think merge it after dev 2.2
(Just don't want to release dev 2.3 Hotfix again, lol)

**Comment by Tommy-XL** [comment]
And also need to synchronize with the last commit in main
image
image

**Comment by NikoCat233** [comment]
LOL

**Comment by Tommy-XL** [comment]
I think I'll merge this after the 1.5.0 release

**Comment by NikoCat233** [comment]
Bruh now so many conflicts

**Comment by NikoCat233** [comment]
I would suggest that for later roles, one role one single rpc and write(byte types) for different conditions

**Comment by NikoCat233** [comment]
@Tommy-XL Pls merge this before it grows bigger

**Comment by Tommy-XL** [comment]
> @Tommy-XL Pls merge this before it grows bigger

Don't worry, I'll merge this first as soon as we finish releasing the Canary version

**Review by Tommy-XL — APPROVED** [review]

**Pull request merged**
