### PR TITLE
/poll + QOL changes

### PR DESCRIPTION
**Pull request by Ultradragon005**
image
image
image

### CODE REVIEW

**Comment by Ultradragon005** [comment]
Me personaly I FW ghadana

**Comment by PHGaming121** [comment]
you should add a {time} to the end of the command, to change the duration of the poll
something like: /poll question A B C time (Example: /poll youre or you're? youre you're both 5 (the poll will end 5 mins after the same was posted in chat))

**Comment by Ultradragon005** [comment]
at best I could make that a setting, but not a part of the command as that would overcomplicate things

**Comment by Tommy-XL** [comment]
It's fully done?

**Comment by Ultradragon005** [comment]
yeah

**Pull request merged**
