### PR TITLE
Make db connect with async

### PR DESCRIPTION
**Pull request by NikoCat233**
@ryuk201198 
you may have to add a flag to check whether db init is access or retry upon exception
Also the hasdevaccess check seems to run before db init and may cause a false flag

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
nope it runs after

**Comment by NikoCat233** [comment]
I gonna rework some checks

**Comment by NikoCat233** [comment]
Can not catch the Exception within Task.Run
idk how to code this, just suffer the lag i guess

**Comment by NikoCat233** [comment]
Oh fuck it still crashes on failure even after I add so many try catch

**Comment by NikoCat233** [comment]
> Oh fuck it still crashes on failure even after I add so many try catch

I cant fix this, lets hang this pr

**Comment by Gurge44** [comment]
When I tried to do async methods, the game straight up just crashed whenever it reached an asynchronous method, no matter what I did....

**Comment by ryuk201198** [comment]
> When I tried to do async methods, the game straight up just crashed whenever it reached an asynchronous method, no matter what I did....

It crashes for me in the authentication code when the authentication failed..

**Comment by NikoCat233** [comment]
Closing this due to Im not able to do this and nobody is doing this

**Comment by NikoCat233** [comment]
Currently this works without crashing the client
But the try-catch cannot catch any exception

**Comment by Tommy-XL** [comment]
Well, does this work fine?

**Comment by Tommy-XL** [comment]
@NikoCat233

**Comment by NikoCat233** [comment]
Should be working

**Review by Tommy-XL — APPROVED** [review]

**Pull request merged**
