### PR TITLE
Added a role Captain

### PR DESCRIPTION
**Pull request by sleepyfor**
Added captain role

### CODE REVIEW

**Comment by NikoCat233** [comment]
God why do u need to format en_us.json

**Comment by sleepyfor** [comment]
> God why do u need to format en_us.json

VS auto formatted it

**Comment by NikoCat233** [comment]
image
Horrible.
Can u revert it?

**Comment by NikoCat233** [comment]
Also role color

**Comment by sleepyfor** [comment]
> image Horrible. Can u revert it?

The formatting looks normal on me screen so idk what’s up

**Comment by Tommy-XL** [comment]
But the Captain is literally a copy of Dictator, just with a new setting...

**Comment by Ultradragon005** [comment]
> But the Captain is literally a copy of Dictator, just with a new setting...

what does it do

**Pull request closed without merging**
