### PR TITLE
Updates and fixes

### PR DESCRIPTION
**Pull request by LezaiYa**

### CODE REVIEW

**Comment by 0xDrMoe** [comment]
@ryuk2098 can you have a look at this and check if all is good? We were in the dev build already I thought? and also, the pic on my end isn't changing

**Comment by ryuk201198** [comment]
what pic?

**Comment by 0xDrMoe** [comment]
the moe one you said you were pushing

**Comment by ryuk201198** [comment]
I havent updated it yet. I will do it with a new Role (porting it from SLE)

**Comment by 0xDrMoe** [comment]
pls push it before you do the role
I want to make that one a dev build

**Comment by ryuk201198** [comment]
PR looks fine. Although are you sure you want to go with that announcement? or do you want to Update it since we are building a new mod and stuff

**Pull request merged**
