### PR TITLE
Disable ShapeShift Menu for Reject Shapeshift roles

### PR DESCRIPTION
**Pull request by Ultradragon005**
so let me explain:
Basically I was messing around with making the player always in a "ShapeShifted" state, so that they would have a portable button to use whenever. BUT RPCRejectShapeshift made it so that it inherits the normal cooldown of the shapeshift, which is actually fantastic. So now I jsut went with that 

In Short:
Made it so that the shapeshift ability button works instantly without needing to open a menu. (it's a seperate method, some roles want to shapeshift)

These roles are testing it:
- pitfall
- Bomber
- Undertaker

Issues to resolve:

- [x] Need to sync it after mushrrom mixup
- More? idk... seems to be working fine for me (tho mind you I only tested with 2 players so idk..)

image

**It's ready for testing now if you want to.**

### CODE REVIEW

**Comment by Ultradragon005** [comment]
incase the gif dosen't load here's the straight link to it : https://i.gyazo.com/679efddb5ad65c7dc716f1ae760145e6.mp4

**Comment by Ultradragon005** [comment]
ignore anything with unshapeshifter timer for now. Because it probably isn't needed.

**Comment by Ultradragon005** [comment]
LOL so this more than likely won't be needed as I asumme they're gonna make phantom button an rpc ( 🙏 ).

**Comment by Ultradragon005** [comment]
so basically innersloth let their 8 year old code phantom and I could'nt get their shitty button to work, so until then I'mma keep this open.

**Comment by Dxgamer7405** [comment]
gurge already did it on ehr

**Comment by Dxgamer7405** [comment]
also works for vanilla too

**Comment by Tommy-XL** [comment]
> gurge already did it on ehr

He just ported this code lol, Drakos opened this PR on May 31st lol

**Comment by Tommy-XL** [comment]
Not only does the phantom's invisibility not work if he desyncs, but his ability button is screwed up on the vanilla side

This is proven by the fact that Innersloth intentionally made roles so that they could not be used in host-only mods.

**Comment by Tommy-XL** [comment]
image

What’s strange is that the vanilla side is first going to go into invisibility and only then checks for invisibility, but on the Host side everything works as it should

**Comment by Dxgamer7405** [comment]
> > gurge already did it on ehr
> 
> He just ported this code lol, Drakos opened this PR on May 31st before new roles and ect.

i didnt know about it lmao

**Comment by Pietrodjaowjao** [comment]
THIS CODE SUCKS

**Comment by Pietrodjaowjao** [comment]
DELETE THIS SHIT NOW

**Comment by Pietrodjaowjao** [comment]
i mEAN @iNNERSLOTH

**Comment by Pietrodjaowjao** [comment]
LET US HAVE ACESS TO AMONG US  SOURCECOXDCE

**Comment by Pietrodjaowjao** [comment]
WE WILL IMPROVE YOUR GAME

**Comment by Gurge44** [comment]
> > gurge already did it on ehr
> 
> He just ported this code lol, Drakos opened this PR on May 31st before new roles and ect.

I didn't even look at this code... my version works completely differently lol

**Comment by Tommy-XL** [comment]
> I didn't even look at this code... my version works completely differently lol

Hmm, ok

**Comment by Ultradragon005** [comment]
image

**Pull request merged**
