### PR TITLE
Add a tag for the translation of the website

### PR DESCRIPTION
**Pull request by LezaiYa1**
Wait for moe to agree, if not agree will close this PR

### CODE REVIEW

**Comment by 0xDrMoe** [comment]
I'd rather have this mitigated completely from the code

**Comment by Ultradragon005** [comment]
since when do chinese people get special tags there's an entire section for specific chinese people

**Comment by LezaiYa1** [comment]
> since when do chinese people get special tags there's an entire section for specific chinese people

TOHE's mod was first made by KARPED1EM, and then it was passed down, and KARPED1EM is Chinese, and the tags for China were added by KARPED1EM, not by us.

**Comment by LezaiYa1** [comment]
> I'd rather have this mitigated completely from the code

What do you mean?

**Comment by NikoCat233** [comment]
意思是他会通过api加，你在discord上面发给他

**Comment by LezaiYa1** [comment]
> 意思是他会通过api加，你在discord上面发给他

我已经开票了啊（

**Pull request closed without merging**
