### PR TITLE
Try Fix Phantom For Desync Roles (PhantomRolePatch.cs)

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Works fine during the game, but if a meeting starts they will see him as a dead impostor

**Comment by Tommy-XL** [comment]
I hope I can fix this shitty role

**Comment by Ultradragon005** [comment]
bruh 🤣

**Comment by Tommy-XL** [comment]
In fact, it would be enough to change the role to reset invisibility, but innersloth is as always

image

**Comment by Ultradragon005** [comment]
they fr did everything in their power to make the rpc as innaccessible ass possible 💀💀

**Comment by Tommy-XL** [comment]
Well, I'm glad that at least it works

image

**Comment by Tommy-XL** [comment]
> Well, I'm glad that at least it works

No it doesn't help, I don't know why

**Pull request merged**
