### PR TITLE
Remove option numbers

### PR DESCRIPTION
**Pull request by Pietrodjaowjao**
Option numbers are actually useless lol

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
i think this pr will change atleast 200 files when its finished

**Comment by NikoCat233** [comment]
I agree that the number is useless
Since you are always passing names

**Comment by Pietrodjaowjao** [comment]
i also made options saving async, if this cause big issues i will revert later

**Comment by Pietrodjaowjao** [comment]
i really dont know when ill finish this, i think its better to merge and then i publish a new row with everything 100% done

**Comment by Ultradragon005** [comment]
260 files changed is crazyyyy

**Comment by Pietrodjaowjao** [comment]
Idk if this correct, is the left still based on rolebase or its main now?

**Comment by Tommy-XL** [comment]
use main now, becouse RoleBase is merget

**Comment by Pietrodjaowjao** [comment]
image
Let it accomolulate ig

**Comment by Ultradragon005** [comment]
fix da conflicts !!

**Comment by Pietrodjaowjao** [comment]
literally all roles have conflicts now lol, i might redo the entire pr soon

**Comment by Tommy-XL** [comment]
The problem is that this change will reset all settings to default because the setting indicator will change

**Comment by Tommy-XL** [comment]
And also, when a setting is added, this will also change the identifier for many settings, right?

**Comment by Ultradragon005** [comment]
> And also, when a setting is added, this will also change the id for many settings, right?

yesn't, if you add a setting inbetween then yeah. Cuz it will rely on the placement in optionholder. Same if a role becomes experimental... so it will constantly remove some preset settings for people

**Comment by Pietrodjaowjao** [comment]
ill rewrite this entire system, it will be based on a attribute or variable name or smth like this

**Comment by Pietrodjaowjao** [comment]
but thats for 2.1.0

**Comment by abdullah2007dhtjtr** [comment]
when 2.1.0 will release

**Comment by Ultradragon005** [comment]
2029

**Comment by KingPanda360** [comment]
> when 2.1.0 will release

The devs said that 2.0.0 won't be released until innersloth fixed their modded protocol issue. We have to wait on Innersloth to fix it, which will take so long because of who they are. So I agree with drakos about the timing. lol

**Comment by Tommy-XL** [comment]
> The rumors are that 2.0.0 won't be released until innersloth fixed their modded protocol issue. We have to wait on Innersloth to fix it, which will take so long because of who they are. So I agree with drakos about the timing. lol

We will release 2.0.0 and if the next AU update breaks the mod, we will simply release a pre-release 2.0.1 and then a full release 2.0.1 with full support vasted version AU

**Comment by abdullah2007dhtjtr** [comment]
Drakos said it will release soon

**Comment by Pietrodjaowjao** [comment]
BRUH

**Comment by Pietrodjaowjao** [comment]
I ACIDENTALLY DELETED THE REPO LMAO

**Comment by Pietrodjaowjao** [comment]
anyways i was going to rewrite this pr soon so no problem at all

**Pull request closed without merging**
