### PR TITLE
Change Role Name Size

### PR DESCRIPTION
**Pull request by Tommy-XL**
Make the displayed role a little larger for modded and vanilla players

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
NOOOOOOO

**Comment by Ultradragon005** [comment]
bro has nightmares

**Comment by KingPanda360** [comment]
> NOOOOOOO

What's wrong with increasing the role size

**Comment by Pietrodjaowjao** [comment]
My screen too small

**Comment by KingPanda360** [comment]
> My screen too small

That seems like a you problem then. 🤣

**Comment by Tommy-XL** [comment]
Someone phones have very small screens, so I decided to change that

**Comment by Tommy-XL** [comment]
I also tested size on PlayStation, where 70% is enough

**Pull request merged**
