### PR TITLE
Add option to hide host text + Translate API tags

### PR DESCRIPTION
**Pull request by Pietrodjaowjao**

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
Please review, you can remove the pt-br translation so it wont bug crowdin.

**Comment by Pietrodjaowjao** [comment]
ig it can be merged now

**Comment by Pietrodjaowjao** [comment]
> ig it can be merged now

@Tommy-XL

**Comment by 0xDrMoe** [comment]
Is this automatic translation? I don't think it should be automatic because some translators don't want it to be in their language. They want just English.

**Comment by Pietrodjaowjao** [comment]
> Is this automatic translation? I don't think it should be automatic because some translators don't want it to be in their language. They want just English.

Nope, i'm brazilian so i know exactly what to put, there's also a error in the original pt-br translation.

Sponsor for some reason is 'Tradutor', it should be 'Patrocinador'

**Comment by Pietrodjaowjao** [comment]
If it doens't bug crowdin, i can put the translations again if you want

**Comment by Pietrodjaowjao** [comment]
If the translator don't want it to be their languague, they can simply leave the original text in translations file.

**Pull request merged**
