### PR TITLE
Support Desync Shapeshifter

### PR DESCRIPTION
**Pull request by Tommy-XL**
- [x] Shapeshifter
- [x] Change code

~~[ ] Phantom~~

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Seems It works fine, but there are some suspicions that there are some bugs that I didn't notice.

**Comment by Tommy-XL** [comment]
Phantom probably needs some changes too

And also need change the code

**Comment by Pietrodjaowjao** [comment]
ok now remove this
image

**Comment by Pietrodjaowjao** [comment]
probably it will even conflict with phantom

**Comment by Gurge44** [comment]
I removed it and it has no impact whatsoever

**Comment by Tommy-XL** [comment]
Well done

**Comment by Ultradragon005** [comment]
WOOOHOOO

**Pull request merged**
