### PR TITLE
Fix pestilence

### PR DESCRIPTION
**Pull request by Ultradragon005**
should fix most the roles, and I do NOT want to mess with exilepatches rn 💀

### CODE REVIEW

**Comment by Ultradragon005** [comment]
image
idk what ya'll doing but FFF rolecolor dosen't correspond to anything

**Comment by ryuk201198** [comment]
@0xDrMoe you forgot to change Hater kn rolecolors.json

**Comment by 0xDrMoe** [comment]
oops

**Comment by Tommy-XL** [comment]
> image idk what ya'll doing but FFF rolecolor dosen't correspond to anything

Fixed

**Review by Tommy-XL — APPROVED** [review]

**Pull request merged**
