### PR TITLE
Revert ""We can't lose the TOHE-Background-Old.jpg".jpg"

### PR DESCRIPTION
**Pull request by Pietrodjaowjao**
Reverts 0xDrMoe/TownofHost-Enhanced#1000

### CODE REVIEW

**Comment by Ultradragon005** [comment]
nop

**Comment by Ultradragon005** [comment]
it was the 100th PR, for christ sake

**Comment by NikoCat233** [comment]
oh no

**Comment by Ultradragon005** [comment]
KURWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Pietrodjaowjao** [comment]
Im going to revert because there is a typo in the name, its saying "We can't lose the TOHE-Background-Old.jpg".jpg instead of "We can't lose the TOHE-Background-Old.jpg"

**Comment by Ultradragon005** [comment]
ban imo

**Comment by NikoCat233** [comment]
gg this pr

**Pull request closed without merging**
