### PR TITLE
Basic fix for EAC

### PR DESCRIPTION
**Pull request by NikoCat233**
Really Basic OK?

### CODE REVIEW

**Comment by NikoCat233** [comment]
1. Add only cancel option for eac handle cheat -- This will make EAC be slient
2. update system check ignores host

**Review by 0xDrMoe — APPROVED** [review]

**Comment by NikoCat233** [comment]
No

**Comment by 0xDrMoe** [comment]
LOL are u not done it?

**Comment by NikoCat233** [comment]
I forget to exclude repairman fix sabotage from eac check

**Comment by NikoCat233** [comment]
Guess ok now, suggest a build to test it

**Review by Tommy-XL — APPROVED** [review]

**Pull request merged**
