### PR TITLE
Rename Anti-Adminer to Cyberpunk

### PR DESCRIPTION
**Pull request by KingPanda360**
The Anti-Adminer needs a better name, 100%. Cyberpunk is a fantastic name because it's similar to what the Anti-Adminer does: hack into devices to find out when people are using them. In the past, KARPED1EM even said that this role needs a better name.

### CODE REVIEW

**Comment by NotPyro404** [comment]
I don't think the name Cyberpunk is good for this role. Maybe something like Interference, not sure.

**Comment by KingPanda360** [comment]
> I don't think the name Cyberpunk is good for this role. Maybe something like Interference, not sure.

I think interference isn't a good word to use as a role name because it seems too simple and broad. Do you have any other name ideas?

**Comment by NotPyro404** [comment]
> I think interference isn't a good word to use as a role name because it seems too simple and broad. Do you have any other name ideas?

Hmm, not really sadly. Maybe Throttler because connection throttled (but that kind of doesn't make sense, I don't know what would be like evil telecommunication)

**Comment by KingPanda360** [comment]
> > I think interference isn't a good word to use as a role name because it seems too simple and broad. Do you have any other name ideas?
> 
> Hmm, not really sadly. Maybe Throttler because connection throttled (but that kind of doesn't make sense, I don't know what would be like evil telecommunication)

Cyberpunk may sound like a bad role name to you, but it fits the description of Anti-Adminer, plus some other people agree with my suggestion. So that's why I made this.

**Comment by NotPyro404** [comment]
> Cyberpunk may sound like a bad role name to you, but it fits the description of Anti-Adminer, plus some other people agree with my suggestion. So that's why I made this.

I guess that's fair.

**Comment by Tommy-XL** [comment]
> I don't think the name Cyberpunk is good for this role. Maybe something like Interference, not sure.

I agree the title is fundamentally inappropriate for this role, and why change it at all?

**Comment by NotPyro404** [comment]
> I agree the title is fundamentally inappropriate for this role, and why change it at all?

Anti-Adminer isn't a great name either, I would prefer a 3rd candidate instead.

**Comment by Ultradragon005** [comment]
GUYS, I have. The perfect name, call it "Blotnik"

**Comment by KingPanda360** [comment]
> Blotnik

Why this?

**Comment by Ultradragon005** [comment]
> Why this?
BLOTNIK!!!!
image

**Comment by KingPanda360** [comment]
> > I don't think the name Cyberpunk is good for this role. Maybe something like Interference, not sure.
> 
> 
> 
> I agree the title is fundamentally inappropriate for this role, and why change it at all?

I wanted to change it because Anti-Adminer didn't seem like a good name for a role. I wanted to make a role name simple and easier to type, say, and spell.

**Comment by Ultradragon005** [comment]
image
good boy

**Comment by Tommy-XL** [comment]
Sorry, lol

image

**Comment by Ultradragon005** [comment]
Oh My goodnes, see. This is why you should've named the PR "Rename Anti-Adminer to Blotnik" and then everything would be fine

**Pull request closed without merging**
