### PR TITLE
add statue

### PR DESCRIPTION
**Pull request by Ultradragon005**
Idea: https://discord.com/channels/1094344790910455908/1180573554476060832

### CODE REVIEW

**Comment by spuhnj** [comment]
I was waiting for Moe to give me a token so I could open a PR for this 😭 (but tbh you did most of the work so it's okay :hehe_sip:)

**Comment by Ultradragon005** [comment]
> I was waiting for Moe to give me a token so I could open a PR for this 😭 (but tbh you did most of the work so it's okay :hehe_sip:)

oh shit mb, I tought since the branch was deleted u didn't wanan try anymore... sorry

**Comment by Ultradragon005** [comment]
well you can look at it to try and figure out what I did

**Comment by spuhnj** [comment]
I never deleted the branch 😭 but really, it's fine, I'll work on another add-on soon now that I mostly know how everything works

**Comment by Ultradragon005** [comment]
somehow I always manage to find errors after marking it as open 😅 well now it is actually done.

**Review by 0xDrMoe — APPROVED** [review]

**Comment by Tommy-XL** [comment]
Fix conflicts, pls

**Comment by Ultradragon005** [comment]
resolved.

**Comment by Tommy-XL** [comment]
Bruh
image

**Comment by Ultradragon005** [comment]
image
weird...

**Comment by Tommy-XL** [comment]
> image

I wanted to combine this here
image

**Comment by Ultradragon005** [comment]
OH I see whatt u did there, you can change it back I will fix the conflicts

**Comment by Tommy-XL** [comment]
Done

**Comment by Ultradragon005** [comment]
it can be merged.

**Review by Tommy-XL — APPROVED** [review]

**Pull request merged**
