### PR TITLE
Jester not being able to get Rebirth

### PR DESCRIPTION
**Pull request by KingPanda360**
If Jester gets the Rebirth add-on, it defeats Jester's purpose and will cause a bug where the Jester will swap skins with whoever's skin they take, and the player who they swapped their skins with will become a ghost, and the Jester will be alive. Plus the names would swap and the victory screen will be wrong.

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Next time patch code on DevBuild and not main
And Rebirth alredy have case
Screenshot_20240905_095902_com android chrome

**Comment by KingPanda360** [comment]
I hate how it doesn't show that whenever I searched for it in customroleshelper.

**Comment by Tommy-XL** [comment]
> I hate how it doesn't show that whenever I searched for it in customroleshelper.

Because you watch the main bratch, need change to DevBuild

**Comment by KingPanda360** [comment]
> > I hate how it doesn't show that whenever I searched for it in customroleshelper.
> 
> Because you watch the main bratch, need change to DevBuild

Oh I see how. Should I close this pr then reopen another for the fix?

**Comment by Tommy-XL** [comment]
Well, you probably don't know how to sync bratch, so you need to open a new

**Comment by KingPanda360** [comment]
> Well, you probably don't know how to sync bratch, so you need to open a new

Ok 👍

**Pull request closed without merging**
