### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by 0xDrMoe**

### CODE REVIEW

**Comment by Tommy-XL** [comment]
I think this is not all the translation changes that were made, he just added a new translation, but what about the changed translation

**Comment by 0xDrMoe** [comment]
these aren't the file names @ryuk2098 they're the commit name it seems. Look at the "Files Changed"

**Comment by ryuk201198** [comment]
Oh okay

**Comment by ryuk201198** [comment]
> I think this is not all the translation changes that were made, he just added a new translation, but what about the changed translation

i think there are many changes that needs to be approved not all the translations have been added in this PR.

**Comment by 0xDrMoe** [comment]
Everything LOOKs fine, it seems like some new lines need to be translated though

**Comment by 0xDrMoe** [comment]
yeah exactly

**Comment by 0xDrMoe** [comment]
good news - Crowdin now auto updates
bad news - more changes are needed

**Comment by 0xDrMoe** [comment]
how does this look to everyone?

**Pull request merged**
