### PR TITLE
Fixes and some changes In "HudSpritePatch"

### PR DESCRIPTION
**Pull request by Tommy-XL**
Update custom sprites only when necessary, as it updates sprites every second

Thanks @D1GQ for fixing a bug where custom sprites are not sets correctly and they become too bright or, conversely, too dark

### CODE REVIEW

**Comment by Tommy-XL** [comment]
> @Tommy-XL There seems to be a bug for shapeshifter roles, where when the shapeshift duration is over if there is one, the icon gets set back to default.

It's not bug, some roles that change the shapeshift status remove the custom icon if necessary

image

**Comment by D1GQ** [comment]
> It's not bug, some roles that change the shapeshift status remove the custom icon if necessary
> 
> image

It was happening to Doll Master and there's no conditions set for it! and this issue has only occurred after I added your fixes.
Screenshot 2024-04-26 073628
So it might be something on my side or it could be a bug.

**Comment by Tommy-XL** [comment]
Try this code

image

```
        // Set custom icon for ability button (Shapeshift, Vitals, Engineer Vent)
        __instance.AbilityButton.graphic.sprite = newAbilityButton;
        __instance.AbilityButton.usesRemainingSprite.sprite = newAbilityButton; // when Shapeshift duraction is remaining
```

**Comment by Tommy-XL** [comment]
Hmm, I reproduced the bug, it's not fixed

**Comment by Tommy-XL** [comment]
Fixed

**Pull request merged**
