### PR TITLE
Re-added dlekS ehT map support

### PR DESCRIPTION
**Pull request by D1GQ**
# Overview
Re-added dlekS ehT map support for ingame lobby.
# Futures
```diff
+ Added dlekS ehT map select support in lobby.
+ Fixed issue where vanilla players would lag in Lobby with dlekS ehT selected!
=== Due to a null reference in the vanilla code the map is spoofed as The Skeld when dlekS ehT is selected.
```

### CODE REVIEW

**Comment by KingPanda360** [comment]
Will the issue where vanilla players can't vent in dlekS ehT be fixed once this is finished?

**Comment by Ultradragon005** [comment]
> Will the issue where vanilla players can't vent in dlekS ehT be fixed once this is finished?

Jit tripping

**Comment by Tommy-XL** [comment]
> Will the issue where vanilla players can't vent in dlekS ehT be fixed once this is finished?

What do you mean?
They can now use ventilation, their arrows are just broken

**Comment by D1GQ** [comment]
> Will the issue where vanilla players can't vent in dlekS ehT be fixed once this is finished?

Yeah that was never a issue to begin with, and it is finished lol.

**Pull request merged**
