### PR TITLE
Fix mod updater for current version number

### PR DESCRIPTION
**Pull request by NikoCat233**
Make ModUpdater directly download dll instead of zip
Force updater and dbconnect to try to use system proxy (if exists)
Add detailed log for dbconnect failed response

Make ModUpdater nolonger use async to avoid crashes (Thanks to Pietro)

*** For further Release ***
The release tag must be v{version_number}
eg v2024.xxxx.xxxx.xxxx
Tags like v1.5.1 will result in wrong result
And it must contains a TOHE.dll for mod updater to download

### CODE REVIEW

**Comment by NikoCat233** [comment]
Gonna to discuss details with our devs

**Comment by Tommy-XL** [comment]
It's done?

**Comment by NikoCat233** [comment]
Its done, but possibly i need to talk with moe on version number thing and add some additional code

**Comment by Tommy-XL** [comment]
Now it's done?

**Comment by NikoCat233** [comment]
Yep

**Pull request merged**
