### PR TITLE
AntiBlack RpcVoting Complete

### PR DESCRIPTION
**Pull request by NikoCat233**
Delayed the restore is dead late task for a while, See comments for reason

For mod clients we show real result, for vanilla clients we show a tie

Also should be fixing player name not changing back if it disconnect during ejection

### CODE REVIEW

**Comment by Tommy-XL** [comment]
I definitely need to improve Anti Blackout as I don't really like the way it works at the moment

**Review by Tommy-XL — APPROVED** [review]

**Comment by Tommy-XL** [comment]
Lol

**Comment by NikoCat233** [comment]
LOL For some reason the exied player name doesnt show

**Comment by Tommy-XL** [comment]
The ejected player's name changes 5 seconds after the vote

**Comment by NikoCat233** [comment]
Fixed

**Pull request merged**
