### PR TITLE
Use Suggestions Visual Studio (Need Update VS to the latest version)

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Tommy-XL** [comment]
It’s not finished yet, but it can be combined now since I don’t know yet when I’ll be able to finish it

**Comment by Tommy-XL** [comment]
Well, i think it's done

**Comment by Tommy-XL** [comment]
Merge it after #462 and maybe afyer #429

**Comment by Ultradragon005** [comment]
this is done?

**Comment by Tommy-XL** [comment]
> this is done?

I need to recheck changes

**Comment by Tommy-XL** [comment]
Well, seems done

**Pull request merged**
