### PR TITLE
LavaChat fix

### PR DESCRIPTION
**Pull request by NetherDragonTw**
thanks for following people for some coding idea!
(Karped, ryuk, Nikocat233)

### CODE REVIEW

**Comment by NikoCat233** [comment]
问一嘴，活着的玩家确保是没有polus驱逐时候的聊天按钮吧

**Comment by NetherDragonTw** [comment]
> 问一嘴，活着的玩家确保是没有polus驱逐时候的聊天按钮吧
> 
> exilecontroler == null很酷炫
我沒在polus上測過

exilecontroler == null是沒有逐出玩家的意思嗎

**Comment by NikoCat233** [comment]
exilecontroler.instance == null 是驱逐动画(界面)实例是否存在的意思

**Comment by Tommy-XL** [comment]
I don’t quite understand what exactly this fixes, you can't send messages during ejections?

**Comment by NikoCat233** [comment]
In polus, when ejecting a player, the chat button for dead players is enabled and they can send message
but toh revive them to prevent them from getting blackouts
So at that short period dead player can send chats and can be seen by other alive players

**Comment by Tommy-XL** [comment]
Yes, I know, but judging by the code, players can no longer send messages during exile?

**Comment by NikoCat233** [comment]
yes.
Message send by dead players would get spammed
In case they tell secrets and influence the left game

**Comment by NetherDragonTw** [comment]
> In polus, when ejecting a player, the chat button for dead players is enabled and they can send message but toh revive them to prevent them from getting blackouts So at that short period dead player can send chats and can be seen by other alive players

nah not only polus
its on every map

**Pull request merged**
