### PR TITLE
Option to hide Shapeshift Animation 

### PR DESCRIPTION
**Pull request by lars-wu**
Option for Dazzler, Devourer, Deathpact and Pitfall to hide the Shapeshift Animation for their Abilities.

I implemented this after reading @Gurge44's comment.
https://discord.com/channels/1094344790910455908/1159602185353580644/1169640524186136707

### CODE REVIEW

**Comment by Tommy-XL** [comment]
I was going to do this too, but as a general setting for all roles with the ability Shapeshift

**Comment by Gurge44** [comment]
Yea and you can also do it for a lot more roles than just these 4. But note that by doing this, you cancel the shapeshift completely, not just the animation. The player will not transform at all. You can see how I've done it in TOHE+.

**Comment by Dawson2763** [comment]
What about Escapist?

**Comment by Gurge44** [comment]
And Miner, Disperser, Evil Tracker, Bomber, Nuker, Quick Shooter, and a lot more roles

**Comment by lars-wu** [comment]
This does not work for vanilla clients unfortunately. After using the shapeshift ability they get stuck and are unable do anything. 
I also tested it in TOHE+ with the same result. Maybe I'm missing something, but seems like it just does not work.

**Comment by Tommy-XL** [comment]
Bad

**Comment by Gurge44** [comment]
I fixed it in my latest commit

**Comment by Ultradragon005** [comment]
I call cap
### **_**A**_**

**Comment by 0xDrMoe** [comment]
whats happening here?

**Comment by lars-wu** [comment]
forgot to close it.

**Pull request closed without merging**
