### PR TITLE
Add a skill icon and role in ChatCommandPatch

### PR DESCRIPTION
**Pull request by LezaiYa**

### CODE REVIEW

**Comment by NikoCat233** [comment]
Empty string?
Can u finish it first?

**Comment by Tommy-XL** [comment]
> Empty string? Can u finish it first?

What?

**Review by Tommy-XL — APPROVED** [review]

**Comment by LezaiYa** [comment]
> Empty string? Can u finish it first?

有空的string也没啥问题吧，前面的是放繁中的，我只是懒得去找繁中的翻译，还不如让阿龙帮我把这个补齐

**Comment by LezaiYa** [comment]
It's all done

**Pull request merged**
